version: '3.7'

services: 
  kafka:
    image: confluentinc/cp-kafka:4.1.0
    container_name: kafka
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: 
      - 9093:9093
    networks: 
      - rekeningku_network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    container_name: zookeeper
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: 
      - rekeningku_network
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9093"
    ports:
      - 8081:8080
    networks:
      - rekeningku_network

networks:
  rekeningku_network:
    external: true